version: '2.1'

networks:
  default:
    driver: bridge

services:
  users-service-builder:
    build: .
    ports:
    - 8080:8080
    container_name: users-service
    image: users-service:latest
    volumes:
    - data:/etc/users-service

volumes:
  data: #holds the information necessary